import Case1 from "../../../public/cases/1.png";
import Case2 from "../../../public/cases/2.png";
import Case3 from "../../../public/cases/3.png";
import Case4 from "../../../public/cases/4.png";
import Case5 from "../../../public/cases/5.png";
import Case6 from "../../../public/cases/6.png";

export interface CaseConfig {
  id: number;
  name: string;
  description: string;
  price: number;
  img: string;
  items: { name: string; price: number; image: string }[];
}

[
  "Taunt: Curious Movements",
  "Inscribed Demon Eater",
  "Bladeform Legacy",
  "Feast of Abscession",
  "Great Sage's Reckoning",
  "Fiery Soul of the Slayer",
  "Blade of the Demonic Vessel",
  "Chains of the Black Death",
  "Pact of the Wurmblood",
  "Genuine Weather Ash",
  "Feast of Abscession Bundle",
  "Mark of the Blood Moon",
  "Inscribed Demon Eater",
  "Bladeform Legacy",
  "Manifold Paradox",
  "Tempest Helm of the Thundergod",
  "Flockheart's Gamble",
];

export const CASES_CONFIG = [
  {
    id: 1,
    name: "Стартовый",
    description: "Стартовый кейс",
    price: 10,
    img: Case1,
    items: [
      { name: "Taunt: Victory Jig", price: 2600 },
      { name: "The International 2014 Music Pack", price: 500 },
      { name: "Draining Wight", price: 2300 },
      { name: "Inscribed Shock of the Anvil", price: 19900 },
      { name: "Provocation of Ruin Mask", price: 239300 },
      { name: "Arcanic Resonance Beam", price: 1100 },
      { name: "Awaleb's Trundleweed", price: 800 },
      { name: "Blossom of the Merry Wanderer", price: 1000 },
      { name: "Dark Maw Inhibitor", price: 1000 },
      { name: "Fate of Hydrophiinae", price: 1100 },
      { name: "Fin of the First Spear", price: 700 },
      { name: "Shadow of the Dark Age", price: 900 },
      { name: "Latticean Hierarchy", price: 500 },
      { name: "Chalice of Ix'yxa", price: 700 },
      { name: "Taunt: The Royal Raspberry", price: 900 },
      { name: "Mask of Metira", price: 700 },
      { name: "Stuntwood Symbiont", price: 900 },
      { name: "Blossom of the Merry Wanderer", price: 1000 },
      { name: "Dark Maw Inhibitor", price: 1000 },
      { name: "Eye of Ix'yxa", price: 400 },
    ],
  },
  {
    id: 2,
    name: "Обычный",
    description: "Обычный кейс",
    price: 9900,
    img: Case2,
    items: [
      { name: "Ripper's Reel", price: 21700 },
      { name: "Edge of the Lost Order", price: 4500 },
      { name: "Yulsaria's Glacier", price: 16100 },
      { name: "The Spoils of Dezun", price: 19400 },
      { name: "Pyrexaec Floe", price: 94100 },
      { name: "Sylvan Cascade", price: 18600 },
      { name: "Chaos Arbiter", price: 19300 },
      { name: "Golden Scavenging Guttleslug", price: 91700 },
      { name: "Hydrakan Latch", price: 24500 },
      { name: "Vigil Signet", price: 11000 },
      { name: "Mask of the Confidant", price: 8700 },
      { name: "Iron Surge", price: 12400 },
      { name: "Hunter's Hoard", price: 69700 },
      { name: "Arms of Desolation", price: 51300 },
      { name: "Crux of Perplex", price: 33800 },
      { name: "Iceflight Edifice", price: 7000 },
      { name: "Colossal Crystal Chorus", price: 3100 },
      { name: "Solar Forge", price: 23200 },
      { name: "Jewel of Aeons", price: 8500 },
      { name: "Peregrine Flight", price: 10800 },
      { name: "Tormented Staff", price: 9000 },
      { name: "Full-Bore Bonanza", price: 4000 },
      { name: "Origins of Faith", price: 31100 },
      { name: "Transversant Soul", price: 9800 },
      { name: "Gimlek Decanter", price: 27600 },
      { name: "Golden Profane Union", price: 11800 },
      { name: "Shearing Deposition", price: 10200 },
      { name: "Golden Ice Blossom", price: 30200 },
      { name: "Genuine Bloodfeather Wings", price: 60300 },
      { name: "Golden Cyrridae", price: 22200 },
      { name: "Piston Impaler", price: 29700 },
      { name: "Blistering Shade", price: 95000 },
      { name: "Offhand Basher of Mage Skulls", price: 6500 },
      { name: "Almond the Frondillo", price: 20600 },
      { name: "Reaper's Wreath", price: 49700 },
      { name: "Rollermawster", price: 8800 },
      { name: "Glaive of Oscilla", price: 39600 },
      { name: "Resistive Pinfold", price: 6400 },
      { name: "Floodmask", price: 57400 },
      { name: "Totem of Deep Magma", price: 14200 },
      { name: "Dam'arakan Muzzle", price: 101200 },
      { name: "Pachyderm Powderwagon Spoon", price: 3800 },
      { name: "Severing Lash", price: 9600 },
      { name: "Siltbreaker Reward", price: 55400 },
      { name: "Thirst of Eztzhok - Off-Hand", price: 33800 },
      { name: "Trust of the Benefactor 2018", price: 20500 },
      { name: "Inscribed The Lightning Orchid", price: 16600 },
      { name: "Dipper the Destroyer", price: 26200 },
      { name: "Inscribed Sylvan Cascade", price: 17300 },
      { name: "Shatterblast Rule", price: 14500 },
      { name: "Draca Maw", price: 2700 },
      { name: "Doll of the Dead", price: 99000 },
      { name: "Inscribed Muh Keen Gun", price: 37900 },
      { name: "Servant of the Sightless Shamans Head", price: 12400 },
      { name: "Inscribed Wraithbinder", price: 6200 },
      { name: "Aktok's Domain", price: 3200 },
      { name: "Armor of the Loyal Fold", price: 76700 },
      { name: "Paragon's Pride Bundle", price: 7300 },
    ],
  },
  {
    id: 3,
    name: "Редкий",
    description: "Редкий кейс",
    price: 30000,
    img: Case3,
    items: [
      { name: "Swift Claw", price: 97300 },
      { name: "Apogee of the Guardian Flame", price: 31200 },
      { name: "Tines of Tybara", price: 24200 },
      { name: "Demon Eater", price: 160100 },
      { name: "Sullen Rampart", price: 66800 },
      { name: "Sylvan Cascade", price: 18600 },
      { name: "Focal Resonance", price: 46000 },
      { name: "Hydrakan Latch", price: 24500 },
      { name: "Iron Surge", price: 12400 },
      { name: "Jagged Honor Blade", price: 79400 },
      { name: "Magus Accord", price: 157800 },
      { name: "Genuine Bloodfeather Wings", price: 60300 },
      { name: "Swine of the Sunken Galley", price: 184300 },
      { name: "Almond the Frondillo", price: 20600 },
      { name: "Blades of the Foulfell Corruptor", price: 131000 },
      { name: "Mulctant Pall", price: 101600 },
      { name: "Glaive of Oscilla", price: 39600 },
      { name: "Dark Artistry Belt", price: 118200 },
      { name: "Blade of the Demonic Vessel", price: 67300 },
      { name: "Flourishing Lodestar", price: 39800 },
      { name: "Golden Ripper's Reel", price: 407700 },
      { name: "Thirst of Eztzhok Blade", price: 45200 },
      { name: "Cape of the Impossible Realm", price: 49500 },
      { name: "Genuine Inverse Bayonet", price: 44600 },
      { name: "Genuine Pale Edge", price: 47900 },
      { name: "Infused Claws of the Ferocious Heart", price: 37000 },
      { name: "Inscribed The Lightning Orchid", price: 16600 },
      { name: "Exalted The Magus Cypher", price: 200800 },
      { name: "Inscribed Blades of Voth Domosh", price: 195000 },
      { name: "Hidden Vector - Blade", price: 45400 },
      { name: "Inscribed Fractal Horns of Inner Abysm", price: 278100 },
      { name: "Inscribed Magus Apex", price: 28700 },
      { name: "Inscribed Vigil Signet", price: 9300 },
      { name: "Mask of the Forgotten Plane", price: 9400 },
      { name: "Astral Origins - Back", price: 67700 },
      { name: "The Abscesserator", price: 38700 },
      { name: "Inscribed Focal Resonance", price: 39300 },
      { name: "Nemestice 2021 Themed Treasure", price: 9400 },
      { name: "Hunger of the Howling Wilds Weapon", price: 11900 },
      { name: "Hidden Vector", price: 80300 },
      { name: "Inscribed Golden Offhand Basher of Mage Skulls", price: 39600 },
      { name: "Inscribed Ripper's Reel", price: 22100 },
      { name: "Inscribed Thirst of Eztzhok Blade", price: 40300 },
      { name: "Tools of the Hellsworn", price: 37600 },
      { name: "Unusual Mango the Newt", price: 63800 },
      { name: "Apex Explorer", price: 9200 },
      { name: "Hunter of the Crystal Drift", price: 46300 },
    ],
  },
  {
    id: 4,
    name: "Эпический",
    description: "Эпический кейс",
    price: 40000,
    img: Case4,
    items: [
      { name: "Grasping Bludgeon", price: 76800 },
      { name: "The Lightning Orchid", price: 19400 },
      { name: "Jagged Honor Mask", price: 52400 },
      { name: "Infernal Chieftain", price: 63700 },
      { name: "Yulsaria's Glacier", price: 16100 },
      { name: "The Spoils of Dezun", price: 19400 },
      { name: "Mantle of the Whispered Bond", price: 21400 },
      { name: "Golden Bloodfeather Feast", price: 16900 },
      { name: "Chaos Arbiter", price: 19300 },
      { name: "Bonkers the Mad", price: 16500 },
      { name: "Mandate of the Stormborn", price: 19500 },
      { name: "Mania's Mask", price: 82200 },
      { name: "Genuine Skittering Desolation", price: 77500 },
      { name: "Dark Artistry Pauldrons", price: 59200 },
      { name: "Golden Edge of the Lost Order", price: 10100 },
      { name: "Bracers of the Cavern Luminar", price: 14900 },
      { name: "Ice Blossom", price: 13900 },
      { name: "The Sunbreeze Birthright", price: 47500 },
      { name: "Genuine Bloodfeather Wings", price: 60300 },
      { name: "Hellborn Grasp", price: 64700 },
      { name: "Piston Impaler", price: 29700 },
      { name: "Swine of the Sunken Galley", price: 184300 },
      { name: "Genuine Molten Claw", price: 71000 },
      { name: "Disciple of the Wyrmwrought Flame", price: 9613 },
      { name: "Scorching Talon", price: 109500 },
      { name: "Feathers of the Vermillion Crucible", price: 153500 },
      { name: "Insatiable Bonesaw", price: 170900 },
      { name: "Genuine Heavy Wingblade", price: 42600 },
      { name: "Antipodean Allies", price: 19500 },
      { name: "Crimson Gates of Nothl", price: 1022600 },
      { name: "Crimson Latticean Hierarchy", price: 947200 },
      { name: "Crimson Progenitor's Bane", price: 961400 },
      { name: "Genuine Claddish Cudgel", price: 162800 },
      { name: "Genuine Hell's Usher", price: 19300 },
      { name: "Genuine Ripper's Reel of the Crimson Witness", price: 1405000 },
      { name: "Genuine The Barb of Skadi", price: 13700 },
      { name: "Immortal Treasure I 2017", price: 16300 },
      { name: "Paraflare Cannon", price: 24900 },
      { name: "Taunt: Come and Get It!", price: 21400 },
      { name: "Taunt: Raging Bull", price: 10500 },
      { name: "Thirst of Eztzhok - Off-Hand", price: 33800 },
      { name: "Trust of the Benefactor 2018", price: 20500 },
      { name: "Hidden Vector - Hat", price: 11900 },
      { name: "Golden Draca Maw", price: 14200 },
      { name: "Immortal Treasure II 2022", price: 9800 },
      { name: "Trust of the Benefactor 2022", price: 20900 },
    ],
  },
  {
    id: 5,
    name: "Мифический",
    description: "Мифический кейс",
    price: 50000,
    img: Case5,
    items: [
      { name: "Ripper's Reel", price: 21700 },
      { name: "Edge of the Lost Order", price: 4500 },
      { name: "Yulsaria's Glacier", price: 16100 },
      { name: "The Spoils of Dezun", price: 19400 },
      { name: "Pyrexaec Floe", price: 94100 },
      { name: "Sylvan Cascade", price: 18600 },
      { name: "Chaos Arbiter", price: 19300 },
      { name: "Golden Scavenging Guttleslug", price: 91700 },
      { name: "Hydrakan Latch", price: 24500 },
      { name: "Vigil Signet", price: 11000 },
      { name: "Mask of the Confidant", price: 8700 },
      { name: "Iron Surge", price: 12400 },
      { name: "Hunter's Hoard", price: 69700 },
      { name: "Arms of Desolation", price: 51300 },
      { name: "Crux of Perplex", price: 33800 },
      { name: "Iceflight Edifice", price: 7000 },
      { name: "Colossal Crystal Chorus", price: 3100 },
      { name: "Solar Forge", price: 23200 },
      { name: "Jewel of Aeons", price: 8500 },
      { name: "Peregrine Flight", price: 10800 },
      { name: "Tormented Staff", price: 9000 },
      { name: "Full-Bore Bonanza", price: 4000 },
      { name: "Origins of Faith", price: 31100 },
      { name: "Transversant Soul", price: 9800 },
      { name: "Gimlek Decanter", price: 27600 },
      { name: "Golden Profane Union", price: 11800 },
      { name: "Shearing Deposition", price: 10200 },
      { name: "Golden Ice Blossom", price: 30200 },
      { name: "Genuine Bloodfeather Wings", price: 60300 },
      { name: "Golden Cyrridae", price: 22200 },
      { name: "Piston Impaler", price: 29700 },
      { name: "Blistering Shade", price: 95000 },
      { name: "Offhand Basher of Mage Skulls", price: 6500 },
      { name: "Almond the Frondillo", price: 20600 },
      { name: "Reaper's Wreath", price: 49700 },
      { name: "Rollermawster", price: 8800 },
      { name: "Glaive of Oscilla", price: 39600 },
      { name: "Resistive Pinfold", price: 6400 },
      { name: "Floodmask", price: 57400 },
      { name: "Totem of Deep Magma", price: 14200 },
      { name: "Dam'arakan Muzzle", price: 101200 },
      { name: "Pachyderm Powderwagon Spoon", price: 3800 },
      { name: "Severing Lash", price: 9600 },
      { name: "Siltbreaker Reward", price: 55400 },
      { name: "Thirst of Eztzhok - Off-Hand", price: 33800 },
      { name: "Trust of the Benefactor 2018", price: 20500 },
      { name: "Inscribed The Lightning Orchid", price: 16600 },
      { name: "Dipper the Destroyer", price: 26200 },
      { name: "Inscribed Sylvan Cascade", price: 17300 },
      { name: "Shatterblast Rule", price: 14500 },
      { name: "Draca Maw", price: 2700 },
      { name: "Doll of the Dead", price: 99000 },
      { name: "Inscribed Muh Keen Gun", price: 37900 },
      { name: "Servant of the Sightless Shamans Head", price: 12400 },
      { name: "Inscribed Wraithbinder", price: 6200 },
      { name: "Aktok's Domain", price: 3200 },
      { name: "Armor of the Loyal Fold", price: 76700 },
      { name: "Paragon's Pride Bundle", price: 7300 },
    ],
  },
  {
    id: 6,
    name: "Легендарный",
    description: "Легендарный кейс",
    price: 64900,
    img: Case6,
    items: [
      { name: "Swift Claw", price: 97300 },
      { name: "Golden Offhand Basher of Mage Skulls", price: 42400 },
      { name: "Concord Dominion", price: 39300 },
      { name: "The Spoils of Dezun", price: 19400 },
      { name: "Pulsar Remnant", price: 24900 },
      { name: "Sullen Rampart", price: 66800 },
      { name: "Golden Scavenging Guttleslug", price: 91700 },
      { name: "Staff of Perplex", price: 89100 },
      { name: "Lamb to the Slaughter", price: 87300 },
      { name: "Crux of Perplex", price: 33800 },
      { name: "Solar Forge", price: 23200 },
      { name: "Cult of Aktok", price: 25300 },
      { name: "Blades of Voth Domosh", price: 202100 },
      { name: "The Sunbreeze Birthright", price: 47500 },
      { name: "Genuine Bloodfeather Wings", price: 60300 },
      { name: "Genuine Rapier of the Burning God Offhand", price: 37600 },
      { name: "Genuine Molten Claw", price: 71000 },
      { name: "Almond the Frondillo", price: 20600 },
      { name: "Reaper's Wreath", price: 49700 },
      { name: "Mask of the Demon Trickster", price: 28100 },
      { name: "Golden Staff of Gun-Yu", price: 369600 },
      { name: "Golden Nothlic Burden", price: 366800 },
      { name: "Alluvion Prophecy", price: 27600 },
      { name: "Armor of the Demon Trickster", price: 419400 },
      { name: "Desert Burn Saddle", price: 157900 },
      { name: "Genuine Hell's Usher", price: 19300 },
      { name: "Paraflare Cannon", price: 24900 },
      { name: "Thirst of Eztzhok - Off-Hand", price: 33800 },
      { name: "Trust of the Benefactor 2018", price: 20500 },
      { name: "Trust of the Benefactor 2019", price: 18500 },
      { name: "Exalted Fractal Horns of Inner Abysm", price: 309500 },
      { name: "Hidden Vector - Blade", price: 45400 },
      { name: "Inscribed Sullen Hollow", price: 91100 },
      { name: "Spring Lineage Pauldrons of Eternal Harvest", price: 115400 },
      { name: "Astral Origins - Back", price: 67700 },
      { name: "Inscribed Fin King's Charm", price: 19600 },
      { name: "Inscribed Shards of Exile", price: 72800 },
      { name: "Provocation of Ruin Bracers", price: 45300 },
      { name: "Guardian Snow Angel", price: 77400 },
    ],
  },
];
