/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CrystalsImport } from './routes/crystals'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const CrystalsRoute = CrystalsImport.update({
  id: '/crystals',
  path: '/crystals',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/crystals': {
      id: '/crystals'
      path: '/crystals'
      fullPath: '/crystals'
      preLoaderRoute: typeof CrystalsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crystals': typeof CrystalsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crystals': typeof CrystalsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/crystals': typeof CrystalsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/crystals'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/crystals'
  id: '__root__' | '/' | '/crystals'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CrystalsRoute: typeof CrystalsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CrystalsRoute: CrystalsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/crystals"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/crystals": {
      "filePath": "crystals.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
